// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjjvxanwrfcxibgtpyau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqanZ4YW53cmZjeGliZ3RweWF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MzgyMzgsImV4cCI6MjA1ODUxNDIzOH0.eEEpQ_wnWt7n8dq7olh4OINhmUkp-sVQ_VFILmRtjzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);